site_name: CInIG-IM

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - mkdocs-pdf

extra_css:
  - stylesheets/extra.css

theme:
  language: es
  name: material    
  palette:
    - scheme: default
      primary: 'deep purple'
      accent: 'purple'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      primary: 'deep purple'
      accent: 'purple'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

  logo: assets/Logos-Blanco-800x268.png
  favicon: assets/favicon.svg

  icon:
    admonition: 
      example: material/file-document-outline

nav:
  - Inicio: index.md
#  - Actividades: actividades.md
#  - Proyectos: proyectos.md
#  - Recursos: recursos.md
  - Integrantes: integrantes.md
#  - Protocolo: protocolo.md
  # - Documentación:
  #     - Introducción: docs/introduccion.md
  #     - Instalación: docs/instalacion.md
  #     - Uso: docs/uso.md
  #     - Configuración: docs/configuracion.md
  # - API: docs/api.md
  # - Contribuir: docs/contribuir.md